'use strict';

/**
 * Finds the unit/building icons for a step's action text.
 *
 * Step actions are free-form text ("Marine, keep producing", "Supply Depot →
 * Barracks"), so terms are matched as substrings, longest first: "Barracks Tech
 * Lab" wins over a bare "Barracks", and "Orbital Command" over "Command Center".
 * Anything unrecognised simply gets no icon and the text stands on its own.
 *
 * The manifest's keys are the terms used by the build files, so this matches
 * whatever vocabulary those are written in.
 *
 * `assets/icons/manifest.json` is generated by `tools/fetch-icons.js`.
 */

const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');

let terms = [];
let baseUrl = null;
let loadError = null;
let haveImages = false;
let shortBy = 0;

/**
 * @param dir directory holding the PNGs and `manifest.json`
 * @returns { count, error } — `error` is reported rather than thrown so a
 *   missing icon set degrades to the text-only overlay instead of no overlay.
 */
function load(dir) {
  terms = [];
  baseUrl = null;
  loadError = null;
  haveImages = false;
  shortBy = 0;
  try {
    const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8'));
    const entries = Object.entries(manifest.terms || {});
    // Longest first so a composed name is preferred over the building inside it.
    entries.sort((a, b) => b[0].length - a[0].length);
    terms = entries.map(([term, file]) => ({ term, file: file + '.png' }));
    baseUrl = pathToFileURL(dir + path.sep).href;
    /* The manifest ships with the app; the images do not — they are fetched on
       request. So a readable manifest says nothing about whether there is
       anything to draw, and on a fresh install there is not.
       Counted rather than sampled, because an update can add a term to the
       manifest that nobody has the picture for yet. Several terms share one
       file — an armour upgrade and its ground-specific name are the same image —
       so files are what gets counted. */
    const files = [...new Set(terms.map((t) => t.file))];
    const here = files.filter((file) => fs.existsSync(path.join(dir, file)));
    haveImages = here.length > 0;
    shortBy = files.length - here.length;
  } catch (err) {
    loadError = err.message;
  }
  return { count: terms.length, error: loadError };
}

/* True only when there are pictures to draw. The control window shows the
   download button on the strength of this, so answering yes for a manifest with
   no images behind it left a new install with empty icon slots and nothing on
   screen explaining how to fill them. */
const loaded = () => terms.length > 0 && haveImages;

/* How many of the manifest's pictures are not on disk. A separate question
   from loaded(): that one asks whether there is anything to draw, this asks
   whether there is anything left to fetch. An install holding every icon of
   the previous version still wants the ones an update added, and offering the
   download button only where there were no pictures at all left nobody a way to
   ask for them. */
const missing = () => shortBy;

/**
 * Icons for one action line, in the order the terms appear in the text.
 * @returns [{ term, src }]
 */
function iconsFor(action, max = 3) {
  const text = String(action || '');
  if (!text || !loaded()) return [];

  const taken = new Array(text.length).fill(false);
  const found = [];

  for (const { term, file } of terms) {
    let from = 0;
    for (;;) {
      const at = text.indexOf(term, from);
      if (at < 0) break;
      from = at + 1;
      let free = true;
      for (let i = at; i < at + term.length; i += 1) if (taken[i]) { free = false; break; }
      if (!free) continue;
      for (let i = at; i < at + term.length; i += 1) taken[i] = true;
      found.push({ at, term, src: baseUrl + file });
    }
  }

  found.sort((a, b) => a.at - b.at);

  // The same picture twice says nothing: "Command Center → Orbital Command"
  // matches the command centre at both ends, and the orbital has no icon of its
  // own to distinguish them.
  const seen = new Set();
  const unique = found.filter(({ src }) => !seen.has(src) && seen.add(src));

  return unique.slice(0, max).map(({ term, src }) => ({ term, src }));
}

/**
 * Every term the manifest knows, for the editor's suggestions.
 *
 * Shortest first — the opposite of the matching order. Matching wants the
 * longest name that fits, so "Barracks Tech Lab" beats "Barracks"; a person
 * typing "Barr" wants to see "Barracks" before "Barracks Tech Lab".
 *
 * `src` is null when the images have not been downloaded, so the caller can
 * offer the names without pretending there are pictures behind them.
 */
function allTerms() {
  const withImages = loaded();
  return [...terms]
    .sort((a, b) => a.term.length - b.term.length || a.term.localeCompare(b.term))
    .map(({ term, file }) => ({ term, src: withImages ? baseUrl + file : null }));
}

module.exports = { load, loaded, missing, iconsFor, allTerms };
